### ISSUE TITLE
Unable to use the json function over a Helia object

### ISSUE THREAD

**Issue by af-afk** [ipfs/helia-json#37]
Hello, when I go to use Helia in a fresh NextJS repo, with the page in client mode, created with `create-next-app`, with this snippet:

```typescript
  useEffect(() => {
    (async () => {
      const h = await createHelia()
      const j = heliaJson(h)
      const r = await j.get("QmUr1PJ3XFKDVYrgjuMUMUXYCFXHXrQfzhzSLHZiwTTi8H")
      console.log("r:", r)
    })()
  }, [])
```

This issue is preceded with a lot of failing to connect to the websockets. An uncaught exception occurs with the following stack trace:

```
memory.js:25 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'bytes')
    at MemoryBlockstore.has (memory.js:25:36)
    at NetworkedStorage.get (networked-storage.js:89:1)
    at BlockStorage.get (storage.js:68:1)
    at async DefaultJSON.get (index.js:41:1)
    at async eval (index.tsx:20:17)
```

The repo with my POC is here: https://github.com/af-afk/helia-issues-undefined-json

I use Brave (1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit)) on Debian Bookworm! Thank you.

**Comment by achingbrain** [comment]
Thanks for opening the issue - the repro repo 404s for me - is it private?

**Comment by SgtPooki** [comment]
The `get` method of `@helia/json` accepts a CID object, not a string, which is why you're getting the `TypeError: Cannot read properties of undefined (reading 'bytes')` error. If you change the code to the below, you will resolve the error you're getting, but you will probably still have an issue, because I can't seem to find that content via [pldiagnose](https://pl-diagnose.on.fleek.co/#/diagnose/access-content?addr=%2Fp2p%2F12D3KooWF3Hb9Vf84qwG8K7fhq4REwXG5ASu4pEAqLcu26Z69cE1&backend=https%3A%2F%2Fpl-diagnose.onrender.com&cid=QmUr1PJ3XFKDVYrgjuMUMUXYCFXHXrQfzhzSLHZiwTTi8H) either.

```
import {CID} from 'multiformats/cid'
  useEffect(() => {
    const cid = CID.parse("QmUr1PJ3XFKDVYrgjuMUMUXYCFXHXrQfzhzSLHZiwTTi8H")
    (async () => {
      const h = await createHelia()
      const j = heliaJson(h)
      const r = await j.get(cid)
      console.log("r:", r)
    })()
  }, [])
```

## A few callouts

### Encoding
FYI, The CID you're using is `dag-pb` (or unixfs) encoded CID, not `json` encoded. See https://cid.ipfs.tech/#QmUr1PJ3XFKDVYrgjuMUMUXYCFXHXrQfzhzSLHZiwTTi8H

### availability on the network

`QmUr1PJ3XFKDVYrgjuMUMUXYCFXHXrQfzhzSLHZiwTTi8H` doesn't seem available when [checking with pl-diagnose](https://pl-diagnose.on.fleek.co/#/diagnose/access-content?addr=%2Fp2p%2F12D3KooWF3Hb9Vf84qwG8K7fhq4REwXG5ASu4pEAqLcu26Z69cE1&backend=https%3A%2F%2Fpl-diagnose.onrender.com&cid=QmUr1PJ3XFKDVYrgjuMUMUXYCFXHXrQfzhzSLHZiwTTi8H), so even when fixing the error (see https://codepen.io/SgtPooki/pen/xxMgoJm?editors=0010), fetching the content fails

![image](https://github.com/ipfs/helia-json/assets/1173416/47eda437-32af-4037-a39e-3592148bdee3)

**Comment by af-afk** [comment]
Hello, thanks for your help. The repo was indeed private, I've made it public now, sorry about that! Thank you for the suggestions. Initially, I used the CID parse, and encountered `Uncaught (in promise) SyntaxError: Unexpected token '', "8
" �_c"... is not valid JSON`, but what you wrote about the CID and the JSON recontextualises things. I've since experimented with the CID using `@helia/strings`, and had success. The data that's in protobuf, I'm too lazy to figure out how to decode, and will in the future make sure isn't encoded this way. What would be a preferable way to do this in the future if the encoding remains the same? Thank you again!

**Comment by achingbrain** [comment]
> Unexpected token '�', "�8 "� �_c�"... is not valid JSON

The `@helia/json` module expects the raw data behind the CID to be interpretable as a string which contains JSON.

Since `QmUr1PJ3XFKDVYrgjuMUMUXYCFXHXrQfzhzSLHZiwTTi8H` is a v0 CID it likely resolves to UnixFS data encoded as a protobuf following the dag-pb schema - this cannot be interpreted as a string that contains JSON, hence the error.

You need to use a decoder that supports the codec your data is encoded with.  Have you tried [@helia/unixfs](https://www.npmjs.com/package/@helia/unixfs)?

..and also yes, as @SgtPooki points out, the Helia APIs generally expect a CID object, not a string containing a CID.

**Comment by SgtPooki** [comment]
> What would be a preferable way to do this in the future if the encoding remains the same? 

@af-afk I would highly recommend looking at the ipld-explorer-components library because it handles encoding/decoding a lot of data, and there's even a `addDagNodeToHelia` helper function we use to build some content-addressable data out of strings and json.

**Comment by af-afk** [comment]
Thank you for the feedback and help! Suggestion noted.
